app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

Route::get('/', array( 'as' => 'home' , function()
{
	return View::make('frontend.index');
}));

Route::get('/about', array( 'as' => 'about', function()
{
	return View::make('frontend.about');
}));

Route::get('/course', array( 'as' => 'course', function()
{
	return View::make('frontend.course');
}));

Route::get('/student_zone', array( 'as' => 'student_zone', function()
{
	return View::make('frontend.student-zone');
}));

Route::get('/course-detail', array( 'as' => 'course-detail', function()
{
	return View::make('frontend.course-detail');
}));

Route::get('/contact', array('as' => 'contact', function()
{
	return View::make('frontend.contact');
}));

Route::get('/syllabus', array('as' => 'syllabus', function()
{
	return View::make('frontend.syllabus');
}));

Route::get('/download', array('as' => 'download', function()
{
	return View::make('frontend.download');
}));

Route::get('/under_construction', array('as' => 'under_construction', function()
{
	return View::make('frontend.error_screen');
}));

Route::resource('users', 'UsersController');
Route::get('register', ['uses' => 'UsersController@create']);
Route::get('login', ['uses' => 'SessionsController@create', 'as' => 'login']);
Route::post('login', ['uses' => 'SessionsController@store', 'as' => 'login']);
Route::get('logout', ['uses' => 'SessionsController@destroy', 'as' => 'logout']);

Route::get('/admin/dashboard', function(){
	return View::make('backend/dashboard');
});

Route::resource('branchs', 'BranchController');
Route::resource('courses', 'CourseController');
Route::resource('syllabus', 'SyllabusController');
Route::resource('subjects', 'SubjectController');
Route::resource('governings', 'GoverningController');
Route::resource('downloads', 'DownloadController');
Route::resource('students', 'StudentController');

app/controllers/BranchController.php
<?php

class BranchController extends \BaseController {

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$branchs = User::where('type', 2)->get()->toArray();
		
		return View::make('backend/branch/index', compact('branchs'));
	}


	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		return View::make('backend/branch/create');
	}


	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store()
	{
		$attrs = Input::all();
		// $branch = User::where('email', $attrs['email']);

		$attrs['type'] = 2; // branch
		if(array_get($attrs, 'password'))
		{
			$password = &$attrs['password'];
			$password = Hash::make($password);
		}
		
		return $this->createNew('User', $attrs);
		// return Redirect::back()->with('message','Operation Successful !');
	}


	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		//
	}


	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$branch = User::findOrFail($id)->toArray();
		// dd($branch);
		return View::make('backend/branch/edit', compact('branch'));
	}


	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
		$branch = User::findOrFail($id);
		$branch->fill(Input::all());
		$branch->save();

	}


	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		//
	}


}

app/views/backend/branch/create.blade.php
@extends('backend/layout/master')

@section('content')
	<div class="row">
            <div class="col-lg-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        Add branch
                    </div>
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-lg-12">
                                {{Form::open(['route' => 'branchs.store'])}}
                                    <div class="form-group">
                                        {{ Form::label('Manager Name') }}
                                        {{ Form::text('manager_name', null, ['class' => 'form-control', 'placeholder' => 'Enter Manager Name', 'autofocus' => 'autofocus']) }}
                                        <span class="alert-danger">{{ $errors->first('manager_name') }}</span>
                                    </div>
                                    <div class="form-group">
                                        {{ Form::label('Email') }}
                                        {{ Form::email('email', null, ['class' => 'form-control', 'placeholder' => 'Enter Email']) }}
                                        <span class="alert-danger">{{ $errors->first('email') }}</span>
                                    </div>
                                    <div class="form-group">
                                        {{ Form::label('Password') }}
                                        {{ Form::password('password', ['class' => 'form-control', 'placeholder' => 'Enter Password']) }}
                                        <span class="alert-danger">{{ $errors->first('password') }}</span>
                                    </div>
                                    <div class="form-group">
                                        {{ Form::label('Contact No.') }}
                                        {{ Form::number('contact', null, ['class' => 'form-control', 'placeholder' => 'Enter Contact No.']) }}
                                        <span class="alert-danger">{{ $errors->first('contact') }}</span>
                                    </div>
                                    <div class="form-group">
                                        {{ Form::label('Address') }}
                                        {{ Form::textarea('address', null, ['class' => 'form-control', 'placeholder' => 'Enter Address']) }}
                                        <span class="alert-danger">{{ $errors->first('address') }}</span>
                                    </div>
                                    <div class="form-group">
                                        {{ Form::submit('Create', ['class' => 'form-control btn btn-primary']) }}
                                    </div>
                                {{ Form::close() }}
                            </div>
                            <!-- /.col-lg-6 (nested) -->
                        </div>
                        <!-- /.row (nested) -->
                    </div>
                    <!-- /.panel-body -->
                </div>
                <!-- /.panel -->
            </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
@stop

app/views/backend/branch/edit.blade.php
@extends('backend/layout/master')

@section('content')
    <div class="row">
            <div class="col-lg-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        Edit branch
                    </div>
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-lg-12">
                                {{Form::open(['route' => 'branchs.store'])}}
                                    <div class="form-group">
                                        {{ Form::label('Manager Name') }}
                                        {{ Form::text('manager_name', $branch['manager_name'], ['class' => 'form-control', 'placeholder' => 'Enter Manager Name', 'autofocus' => 'autofocus']) }}
                                        <span class="alert-danger">{{ $errors->first('manager_name') }}</span>
                                    </div>
                                    <div class="form-group">
                                        {{ Form::label('Email') }}
                                        {{ Form::email('email', $branch['email'], ['class' => 'form-control', 'placeholder' => 'Enter Email']) }}
                                        <span class="alert-danger">{{ $errors->first('email') }}</span>
                                    </div>
                                    <div class="form-group">
                                        {{ Form::label('Contact No.') }}
                                        {{ Form::number('contact', $branch['contact'], ['class' => 'form-control', 'placeholder' => 'Enter Contact No.']) }}
                                        <span class="alert-danger">{{ $errors->first('contact') }}</span>
                                    </div>
                                    <div class="form-group">
                                        {{ Form::label('Address') }}
                                        {{ Form::textarea('address', $branch['address'], ['class' => 'form-control', 'placeholder' => 'Enter Address']) }}
                                        <span class="alert-danger">{{ $errors->first('address') }}</span>
                                    </div>
                                    <div class="form-group">
                                        {{ Form::submit('Update', ['class' => 'form-control btn btn-primary']) }}
                                    </div>
                                {{ Form::close() }}
                            </div>
                            <!-- /.col-lg-6 (nested) -->
                        </div>
                        <!-- /.row (nested) -->
                    </div>
                    <!-- /.panel-body -->
                </div>
                <!-- /.panel -->
            </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
@stop

app/views/backend/branch/index.blade.php
@extends('backend/layout/master')

@section('content')
	<div class="row">
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            Branch lists
                        </div>
                        <!-- /.panel-heading -->
                        <div class="panel-body">
                            <div class="dataTable_wrapper">
                                <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                                    <thead>
                                        <tr>
                                            <th>Manager Name</th>
                                            <th>Email</th>
                                            <th>Contact</th>
                                            <th>Address</th>
                                            <th>Action</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach ($branchs as $b )
                                                                             
                                        <tr class="odd gradeX">
                                            <td>{{ $b['manager_name'] }}</td>
                                            <td>{{ $b['email'] }}</td>
                                            <td>{{ $b['contact'] }}</td>
                                            <td>{{ $b['address'] }}</td>
                                            <td>{{ link_to_route('branchs.edit', 'Edit', $b['id']) }}</td>
                                        </tr>
                                        @endforeach
                                    </tbody>
                                </table>
                            </div>
                            <!-- /.table-responsive -->
                        </div>
                        <!-- /.panel-body -->
                    </div>
                    <!-- /.panel -->
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
@stop