app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

Route::get('/', array( 'as' => 'home' , function()
{
	return View::make('frontend.index');
}));

Route::get('/about', array( 'as' => 'about', function()
{
	return View::make('frontend.about');
}));

Route::get('/course', array( 'as' => 'course', function()
{
	return View::make('frontend.course');
}));

Route::get('/student_zone', array( 'as' => 'student_zone', function()
{
	return View::make('frontend.student-zone');
}));

Route::get('/course-detail', array( 'as' => 'course-detail', function()
{
	return View::make('frontend.course-detail');
}));

Route::get('/contact', array('as' => 'contact', function()
{
	return View::make('frontend.contact');
}));

Route::get('/syllabus', array('as' => 'syllabus', function()
{
	return View::make('frontend.syllabus');
}));

Route::get('/download', array('as' => 'download', function()
{
	return View::make('frontend.download');
}));

Route::get('/under_construction', array('as' => 'under_construction', function()
{
	return View::make('frontend.error_screen');
}));

Route::resource('users', 'UsersController');
Route::get('register', ['uses' => 'UsersController@create']);
Route::get('login', ['uses' => 'SessionsController@create', 'as' => 'login']);
Route::post('login', ['uses' => 'SessionsController@store', 'as' => 'login']);
Route::get('logout', ['uses' => 'SessionsController@destroy', 'as' => 'logout']);

Route::get('/admin/dashboard', function(){
	return View::make('backend/dashboard');
});

Route::resource('branchs', 'BranchController');
Route::resource('courses', 'CourseController');
Route::resource('syllabus', 'SyllabusController');
Route::resource('subjects', 'SubjectController');
Route::resource('governings', 'GoverningController');
Route::resource('downloads', 'DownloadController');
Route::resource('students', 'StudentController');

app/models/Syllabus.php
<?php

use app\models\Course;

class Syllabus extends ApiModel {

	/**
	 * The database table used by the model.
	 *
	 * @var string
	 */
	protected $table = 'syllabus';

	public static $rules = [
		// 'course_id'		=> 'required',
		'title'			=> 'required'
	];

	protected $fillable = ['title'];

	public function course(){
		return $this->belongsTo('Course', 'id');
	}

	public function subjects(){
		return $this->hasMany('Subject');
	}
}

app/controllers/SyllabusController.php
<?php

class SyllabusController extends \BaseController {

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$syllabus = Syllabus::get()->toArray();
		return View::make('backend/syllabus/index', compact('syllabus'));
	}


	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		$courses = Course::lists('title', 'id');
		// dd($courses);
		return View::make('backend/syllabus/create', compact('courses'));
	}


	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store()
	{
		$attrs = Input::all();
		$syllabus =  $this->createNew('Syllabus', $attrs);
		// dd($syllabus);
		DB::table('course_syllabus')->insert(['course_id' => $attrs['course_id'], 'syllabus_id' =>  $syllabus['id'] ]);
	}


	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		//
	}


	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		// dd($id);
		// $syllabus = Syllabus::whereId($id)->with(['course'])->get()->toArray();
		// $syllabus = Syllabus::where('id', $id)->with(['course'])->lists('id', 'title');
		// $syllabus = Syllabus::findOrFail($id)->with(['course'])->first()->toArray();
		// dd($syllabus);
		$courses = Course::lists('title', 'id');
		return View::make('backend/syllabus/edit', compact('syllabus', 'courses'));
	}


	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
		//
	}


	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		//
	}


}

app/views/backend/syllabus/create.blade.php
@extends('backend/layout/master')

@section('content')
	<div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Add Syllabus
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-lg-12">
                            {{-- <form role="form"> --}}
                            {{Form::open(['route' => 'syllabus.store'])}}
                            	<div class="form-group">
                                    {{ Form::label('Course') }}
                                    {{ Form::select('course_id', $courses, null, ['class' => 'form-control', 'autofocus' => 'autofocus']) }}
                                    <span class="alert-danger">{{ $errors->first('course_id') }}</span>
                                </div>
                                <div class="form-group">
                                    {{ Form::label('Title') }}
                                    {{ Form::text('title', null, ['class' => 'form-control', 'placeholder' => 'Enter Title']) }}
                                    <span class="alert-danger">{{ $errors->first('title') }}</span>
                                </div>
                                <div class="form-group">
                                    {{ Form::submit('Create', ['class' => 'form-control btn btn-primary']) }}
                                </div>
                            {{-- </form> --}}
                            {{ Form::close() }}
                        </div>
                        <!-- /.col-lg-6 (nested) -->
                    </div>
                    <!-- /.row (nested) -->
                </div>
                <!-- /.panel-body -->
            </div>
            <!-- /.panel -->
        </div>
            <!-- /.col-lg-12 -->
        </div>
            <!-- /.row -->
@stop

app/views/backend/syllabus/edit.blade.php
@extends('backend/layout/master')

@section('content')
	<div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Edit Syllabus
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-lg-12">
                            {{-- <form role="form"> --}}
                            {{Form::open(['route' => 'syllabus.store'])}}
                            	<div class="form-group">
                                    {{ Form::label('Course') }}
                                    {{ Form::select('course_id', $courses, $syllabus['course']['id'], ['class' => 'form-control', 'autofocus' => 'autofocus']) }}
                                    <span class="alert-danger">{{ $errors->first('course_id') }}</span>
                                </div>
                                <div class="form-group">
                                    {{ Form::label('Title') }}
                                    {{ Form::text('title', $syllabus['title'], ['class' => 'form-control', 'placeholder' => 'Enter Title']) }}
                                    <span class="alert-danger">{{ $errors->first('title') }}</span>
                                </div>
                                <div class="form-group">
                                    {{ Form::submit('Create', ['class' => 'form-control btn btn-primary']) }}
                                </div>
                            {{-- </form> --}}
                            {{ Form::close() }}
                        </div>
                        <!-- /.col-lg-6 (nested) -->
                    </div>
                    <!-- /.row (nested) -->
                </div>
                <!-- /.panel-body -->
            </div>
            <!-- /.panel -->
        </div>
            <!-- /.col-lg-12 -->
        </div>
            <!-- /.row -->
@stop

app/views/backend/syllabus/index.blade.php
@extends('backend/layout/master')

@section('content')
	<div class="row">
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            Syllabus lists
                        </div>
                        <!-- /.panel-heading -->
                        <div class="panel-body">
                            <div class="dataTable_wrapper">
                                <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                                    <thead>
                                        <tr>
                                            <th>Title</th>
                                            <th>Action</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach ($syllabus as $s )
                                                                             
                                        <tr class="odd gradeX">
                                            <td>{{ $s['title'] }}</td>
                                            <td>{{ link_to_route('syllabus.edit', 'Edit', $s['id']) }}</td>
                                        </tr>
                                        @endforeach
                                    </tbody>
                                </table>
                            </div>
                            <!-- /.table-responsive -->
                        </div>
                        <!-- /.panel-body -->
                    </div>
                    <!-- /.panel -->
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
@stop